### ISSUE TITLE
Compass_config.xml file on dedicated server

### ISSUE THREAD

**Issue by mngrazy** [DeckerMMIV/FarmSim_Mod_Compass#5]
hi decker

the v2.0.6 create a xml file on the dedicated server

can you fix it ?

best regards mngrazy

**Comment by DeckerMMIV** [comment]
@mngrazy - Try v2.0.7 and please tell me if it solved the problem.

**Comment by mngrazy** [comment]
** Compass seems to be running on a dedicated-server. So will not create 'Compass_config.xml' file.

dont create the xml file now ,,, thank you decker !

regards grazy
