### ISSUE TITLE
Adapting localization

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [DeckerMMIV/FarmSim_Mod_Compass#9]
Some changes needed to adapt the Russian localization.
https://drive.google.com/file/d/0B_zrlMUSl3roajNyUkI1ZEdlTzA/view?usp=sharing

It is necessary to translate the line 219 and 230.

**Comment by DeckerMMIV** [comment]
Yeah, that looks bad.
I will attempt to fix the calculations for width, so they consider translated text.

**Comment by DeckerMMIV** [comment]
Hopefully fixed with v1.0.0.18
Will wait a bit before publishing on ModHub, as there might be other things to update - ... like some new translations ;)

**Comment by Gonimy-Vetrom** [comment]
Now it looks better.

Thank you.
